name: MacOS-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4ÃŸ
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: CMake set-up
        run: cmake -G "Unix Makefiles" -DHMDF_TESTING=ON -DHMDF_EXAMPLES=ON -DHMDF_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release .
      - name: CMake build
        run: cmake --build .
      - name: CMake ctest
        run: ctest -C Release
